### ISSUE TITLE
default.node_sound_*_defaults are functions, not tables. So add ()

### ISSUE THREAD

**Issue by wziard** [Sokomine/cottages#10]
When I click a mob from mobs_redo with any object from cottages, I get a crash.

This is because default.node_sound_*_defaults are functions, not tables. But they are not called, but copied. Making sounds a function instead of a table.

Patch attached.

[snip] garbled patch deleted

**Comment by wziard** [comment]
Oh, that patch didn't survive my chain of copy-pasting to get it from my vpn to github :-)

patch attached.

[patch.txt](https://github.com/Sokomine/cottages/files/2753440/patch.txt)

**Comment by Sokomine** [comment]
Thank you for noticing that bug! It ought to be fixed in the newest version.
The sounds need some special care as some games (i.e. MC2) do not provide a suitable default mod.
