### ISSUE TITLE
Craft reciep conflict with default steel sign

### ISSUE THREAD

**Issue by adrido** [Sokomine/cottages#2]
The default steel sign uses the same craft reciep as the hammer
![craft hammer](https://cloud.githubusercontent.com/assets/3142688/16659584/0e70efcc-446b-11e6-9ff1-2753e218bd40.png)
![craft sign](https://cloud.githubusercontent.com/assets/3142688/16659583/0e5a7f26-446b-11e6-9dfc-415a12c66611.png)

**Comment by mase76** [comment]
I can confirm this. I have to disable cottages temporarely to build a steel sign.

**Comment by Sokomine** [comment]
Thanks for reporting. It has been changed in the meantime and ought to work without conflict now (an anvil is needed to craft the hammer).
